# Generated by Django 4.1 on 2022-08-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agf_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_no', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='area_documents', to='agf_assets.area')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('drawing', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sub_types', to='agf_documents.documenttype')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=10)),
                ('reason', models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Issue for Review'), (3, 'Issue for Construction'), (4, 'Issue for Demolition'), (5, 'Issue for Tender'), (6, 'Issue for Quotation'), (7, 'Issue for Information'), (99, 'As Built')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Current Revision'), (3, 'Superseded'), (4, 'Obsolete'), (5, 'Archived')])),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='agf_documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_documents', to='agf_documents.document')),
                ('reference_document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documents_referred_by', to='agf_documents.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sub_type_documents', to='agf_documents.documentsubtype'),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='type_documents', to='agf_documents.documenttype'),
        ),
    ]
