# Generated by Django 4.1 on 2022-08-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agf_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrevision',
            name='reason',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Issue for Review'), (3, 'Issue for Construction'), (4, 'Issue for Demolition'), (5, 'Issue for Tender'), (6, 'Issue for Quotation'), (7, 'Issue for Information'), (9, 'Issue for HAZOP'), (99, 'As Built')]),
        ),
        migrations.AlterField(
            model_name='documentrevision',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Current Issue'), (3, 'Superseded'), (4, 'Obsolete'), (5, 'Archived')]),
        ),
    ]
