# Generated by Django 4.1 on 2022-08-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agf_documents', '0002_alter_documentrevision_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sequential_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
