# Generated by Django 4.1 on 2022-08-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agf_documents', '0005_alter_documentrevision_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sheet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
