# Generated by Django 4.1 on 2022-11-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agf_documents', '0007_alter_documentrevision_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrevision',
            name='reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Draft'), (7, 'Issue for Information'), (10, 'Issue for Comment'), (2, 'Issue for Review'), (9, 'Issue for HAZOP'), (6, 'Issue for Quotation'), (5, 'Issue for Tender'), (3, 'Issue for Construction'), (4, 'Issue for Demolition'), (8, 'Issue for Use'), (99, 'As Built')], null=True),
        ),
    ]
