# Generated by Django 4.1 on 2022-12-05 12:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agf_assets', '0015_alter_area_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField()),
                ('utilisation', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_complete', models.DateField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pms', to='agf_assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='PM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Schedule'), (2, 'Rotating Equipment')])),
                ('units', models.PositiveSmallIntegerField(choices=[(0, 'hours'), (1, 'days'), (2, 'weeks'), (3, 'months')])),
                ('frequency', models.IntegerField()),
                ('sch_type', models.PositiveSmallIntegerField(choices=[(1, 'From last'), (2, 'Fixed Schedule')])),
                ('sch_ahead', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Urgent'), (2, 'Priority'), (3, 'Normal')])),
                ('sch_date', models.DateField()),
                ('complete_date', models.DateField(blank=True, null=True)),
                ('lock_sch', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='wos', to='agf_assets.asset')),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='wos', to='agf_maintenance.assetpm')),
            ],
        ),
        migrations.CreateModel(
            name='WOTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agf_maintenance.pm')),
                ('wo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agf_maintenance.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField()),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agf_maintenance.pm')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='agf_maintenance.pm')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_id', models.PositiveIntegerField()),
                ('force_sch', models.BooleanField()),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodcedures', to='agf_maintenance.pm')),
            ],
        ),
        migrations.AddField(
            model_name='assetpm',
            name='last_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='agf_maintenance.procedure'),
        ),
        migrations.AddField(
            model_name='assetpm',
            name='pm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assets', to='agf_maintenance.pm'),
        ),
    ]
