# Generated by Django 4.1 on 2023-04-04 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_documents', '0008_alter_documentrevision_reason'),
        ('agf_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='force_sch',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='pm',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='sequence_id',
        ),
        migrations.AddField(
            model_name='procedure',
            name='name',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProcedureSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Supression'), (2, 'Simple Schedule')])),
                ('sequence', models.PositiveIntegerField()),
                ('force_sch', models.BooleanField()),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodcedures', to='agf_maintenance.pm')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='agf_documents.document')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agf_maintenance.pm')),
            ],
        ),
    ]
