# Generated by Django 4.1 on 2023-04-04 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_maintenance', '0002_remove_procedure_force_sch_remove_procedure_pm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedureschedule',
            name='type',
        ),
        migrations.AddField(
            model_name='pm',
            name='force_sch',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedureschedule',
            name='procedure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agf_maintenance.pm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pm',
            name='sch_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Supression'), (2, 'Simple Schedule')]),
        ),
        migrations.AlterField(
            model_name='procedureschedule',
            name='pm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='agf_maintenance.pm'),
        ),
    ]
