# Generated by Django 4.1 on 2023-04-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agf_maintenance', '0003_remove_procedureschedule_type_pm_force_sch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedureschedule',
            name='force_sch',
        ),
    ]
