# Generated by Django 4.1 on 2023-04-04 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_maintenance', '0004_remove_procedureschedule_force_sch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedureschedule',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pms', to='agf_maintenance.pm'),
        ),
    ]
