# Generated by Django 4.1 on 2023-04-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agf_maintenance', '0005_alter_procedureschedule_procedure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedureschedule',
            options={'ordering': ['sequence']},
        ),
    ]
