# Generated by Django 4.1 on 2023-04-04 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_maintenance', '0006_alter_procedureschedule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedureschedule',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pms', to='agf_maintenance.procedure'),
        ),
    ]
