# Generated by Django 4.1 on 2023-04-04 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agf_maintenance', '0007_alter_procedureschedule_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetpm',
            name='last_procedure',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='assetpm',
            name='utilisation',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
