# Generated by Django 4.1 on 2023-04-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agf_maintenance', '0008_alter_assetpm_last_procedure_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceduretask',
            options={'ordering': ['no']},
        ),
    ]
