# Generated by Django 4.1 on 2023-04-04 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_maintenance', '0009_alter_proceduretask_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduredocuments',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agf_maintenance.procedure'),
        ),
        migrations.AlterField(
            model_name='proceduretask',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agf_maintenance.procedure'),
        ),
        migrations.AlterField(
            model_name='proceduretask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='agf_maintenance.task'),
        ),
    ]
