# Generated by Django 4.1 on 2023-04-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agf_maintenance', '0010_alter_proceduredocuments_procedure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetpm',
            name='last_deployed',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
