# Generated by Django 4.1 on 2023-05-03 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_maintenance', '0011_assetpm_last_deployed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='wos', to='agf_maintenance.assetpm'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Immediate'), (2, 'Urgent'), (3, 'Normal')]),
        ),
    ]
