# Generated by Django 4.1 on 2023-06-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agf_maintenance', '0012_alter_workorder_pm_alter_workorder_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Deployed'), (2, 'On Hold'), (3, 'Completed'), (9, 'Cancelled')], default=1),
            preserve_default=False,
        ),
    ]
