# Generated by Django 4.1 on 2023-06-09 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_maintenance', '0013_workorder_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wotask',
            options={'ordering': ['no']},
        ),
        migrations.AlterField(
            model_name='proceduretask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='procedures', to='agf_maintenance.task'),
        ),
    ]
