# Generated by Django 4.1 on 2023-07-19 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_documents', '0008_alter_documentrevision_reason'),
        ('agf_maintenance', '0015_alter_wotask_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='WODocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='agf_documents.document')),
                ('wo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agf_maintenance.workorder')),
            ],
        ),
    ]
