# Generated by Django 4.1 on 2022-10-18 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agf_hse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire',
            name='pass_mark',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionaire',
            name='show_marking',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Multiple Choice'), (2, 'Select All Applicable'), (3, 'Written Answer')]),
        ),
    ]
