# Generated by Django 4.1 on 2022-10-18 23:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agf_hse', '0005_rename_questionaireemailresults_questionaireemailresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionaireEmailResult',
            new_name='QuestionaireEmailResults',
        ),
    ]
