# Generated by Django 4.1 on 2022-10-19 00:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agf_hse', '0006_rename_questionaireemailresult_questionaireemailresults'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionaireEmailResults',
            new_name='QuestionaireEmailResult',
        ),
        migrations.RenameModel(
            old_name='Questionaire',
            new_name='Questionnaire',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionaire',
            new_name='questionnaire',
        ),
        migrations.RenameField(
            model_name='questionaireemailresult',
            old_name='questionaire',
            new_name='questionnaire',
        ),
    ]
