# Generated by Django 4.1 on 2022-10-19 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_hse', '0008_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaireemailresult',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='agf_hse.questionnaire'),
        ),
    ]
