# Generated by Django 4.1 on 2023-05-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agf_hse', '0010_questionaireresults_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionaireemailresult',
            name='description',
        ),
        migrations.RemoveField(
            model_name='questionaireemailresult',
            name='instructions',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='instructions',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
