# Generated by Django 4.1 on 2023-05-15 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_hse', '0011_remove_questionaireemailresult_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaireresults',
            name='passed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionaireresultsanswers',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='agf_hse.answer'),
        ),
    ]
