# Generated by Django 4.1 on 2022-08-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequential_no', models.IntegerField()),
                ('suffix', models.CharField(blank=True, max_length=3, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'In Service'), (2, 'Out of Service'), (3, 'Removed')])),
                ('legacy_no', models.CharField(blank=True, max_length=255, null=True)),
                ('valve_spec', models.CharField(blank=True, max_length=10, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_no', models.CharField(max_length=255)),
                ('security_held', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('annual_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LineContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LineRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PetroleumLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Authority to Prospect'), (2, 'Petroleum License'), (3, 'Petroleum Pipeline License'), (4, 'Petroleum Facility License'), (5, 'Prospective Commercial Area')])),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('granted', models.DateField()),
                ('term', models.IntegerField()),
                ('extension_start', models.DateField(blank=True, null=True)),
                ('extension_term', models.IntegerField()),
                ('epa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='petroleum_licenses', to='agf_assets.epa')),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='category_types', to='agf_assets.assetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AssetHierachy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parent', to='agf_assets.asset')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='agf_assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDocumentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asset_document_reference', to='agf_assets.asset')),
            ],
        ),
    ]
