# Generated by Django 4.1 on 2022-08-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agf_assets', '0001_initial'),
        ('agf_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdocumentreference',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assets_referred_by', to='agf_documents.document'),
        ),
        migrations.AddField(
            model_name='asset',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='area_assets', to='agf_assets.area'),
        ),
        migrations.AddField(
            model_name='asset',
            name='line_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='line_content_assets', to='agf_assets.linecontent'),
        ),
        migrations.AddField(
            model_name='asset',
            name='line_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='line_rating_assets', to='agf_assets.linerating'),
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='type_assets', to='agf_assets.assettype'),
        ),
        migrations.AddField(
            model_name='area',
            name='permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='areas', to='agf_assets.petroleumlicence'),
        ),
    ]
