# Generated by Django 4.1 on 2022-08-25 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petroleumlicence',
            name='epa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='petroleum_licenses', to='agf_assets.epa'),
        ),
    ]
