# Generated by Django 4.1 on 2022-08-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agf_assets', '0003_alter_petroleumlicence_epa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petroleumlicence',
            name='extension_term',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
