# Generated by Django 4.1 on 2022-08-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agf_assets', '0005_petroleumlicence_status_replacementpl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petroleumlicence',
            name='granted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petroleumlicence',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Expired'), (3, 'Cancelled'), (3, 'Application')]),
        ),
        migrations.AlterField(
            model_name='petroleumlicence',
            name='term',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
