# Generated by Django 4.1 on 2022-09-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agf_assets', '0006_alter_petroleumlicence_granted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
