# Generated by Django 4.1 on 2022-11-01 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_assets', '0009_delete_assethierachy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='areas', to='agf_assets.petroleumlicence'),
        ),
    ]
