# Generated by Django 4.1 on 2022-11-29 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_assets', '0010_alter_area_permit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Exploration'), (2, 'Appraisal'), (3, 'Production')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Producing'), (2, 'Suspended'), (3, 'Abandoned')])),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('rotary_table', models.FloatField(blank=True, null=True)),
                ('total_depth', models.FloatField(blank=True, null=True)),
                ('spud_date', models.DateField(blank=True, null=True)),
                ('rig_release_date', models.DateField(blank=True, null=True)),
                ('plug_date', models.DateField(blank=True, null=True)),
                ('MAASP', models.FloatField(blank=True, null=True)),
                ('MAWOP', models.FloatField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='well_details', to='agf_assets.asset')),
            ],
        ),
    ]
