# Generated by Django 4.1 on 2022-11-30 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_assets', '0013_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='agf_assets.region'),
            preserve_default=False,
        ),
    ]
