# Generated by Django 4.1 on 2022-08-24 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequential_no', models.IntegerField()),
                ('suffix', models.CharField(blank=True, max_length=3, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'In Service'), (2, 'Out of Service'), (3, 'Removed')])),
                ('legacy_no', models.CharField(blank=True, max_length=255, null=True)),
                ('valve_spec', models.CharField(blank=True, max_length=10, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='area_assets', to='agf.area')),
            ],
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_no', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='area_documents', to='agf.area')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('drawing', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_no', models.CharField(max_length=255)),
                ('security_held', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('annual_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=1000)),
                ('ext', models.CharField(max_length=10)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LineContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LineRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PetroleumLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Authority to Prospect'), (2, 'Petroleum License'), (3, 'Petroleum Pipeline License'), (4, 'Petroleum Facility License'), (5, 'Prospective Commercial Area')])),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('granted', models.DateField()),
                ('term', models.IntegerField()),
                ('extension_start', models.DateField(blank=True, null=True)),
                ('extension_term', models.IntegerField()),
                ('epa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='petroleum_licenses', to='agf.epa')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='file_image', to='agf.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sub_types', to='agf.documenttype')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=10)),
                ('reason', models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Issue for Review'), (3, 'Issue for Construction'), (4, 'Issue for Demolition'), (5, 'Issue for Tender'), (6, 'Issue for Quotation'), (7, 'Issue for Information'), (99, 'As Built')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Current Revision'), (3, 'Superseded'), (4, 'Obsolete'), (5, 'Archived')])),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='agf.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_documents', to='agf.document')),
                ('reference_document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documents_referred_by', to='agf.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='document_files', to='agf.document')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='file_document', to='agf.file')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sub_type_documents', to='agf.documentsubtype'),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='type_documents', to='agf.documenttype'),
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='category_types', to='agf.assetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=False)),
                ('nameplate', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asset_images', to='agf.asset')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='image_assets', to='agf.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetHierachy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parent', to='agf.asset')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='agf.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDocumentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asset_document_reference', to='agf.asset')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assets_referred_by', to='agf.document')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='line_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='line_content_assets', to='agf.linecontent'),
        ),
        migrations.AddField(
            model_name='asset',
            name='line_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='line_rating_assets', to='agf.linerating'),
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='type_assets', to='agf.assettype'),
        ),
        migrations.AddField(
            model_name='area',
            name='permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='areas', to='agf.petroleumlicence'),
        ),
    ]
