# Generated by Django 4.1 on 2022-08-27 23:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_documents', '0006_document_sheet_document_suffix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agf_files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfile',
            name='document',
        ),
        migrations.RemoveField(
            model_name='file',
            name='size',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.AddField(
            model_name='documentfile',
            name='document_revision',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='document_files', to='agf_documents.documentrevision'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='ph',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='pw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FileMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_files', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
