# Generated by Django 4.1 on 2022-08-28 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agf_files', '0002_remove_documentfile_document_remove_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemeta',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='file_metadata', to='agf_files.file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filemeta',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filemeta',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='modified_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
