# Generated by Django 4.1 on 2022-09-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_files', '0003_filemeta_file_alter_filemeta_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemeta',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_metadata', to='agf_files.file'),
        ),
    ]
