# Generated by Django 4.1 on 2022-10-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_documents', '0006_document_sheet_document_suffix'),
        ('agf_files', '0005_alter_assetimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='document_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_files', to='agf_documents.documentrevision'),
        ),
    ]
