# Generated by Django 4.1 on 2022-12-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agf_files', '0007_documentfile_link_expiry_documentfile_public_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='public_link',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
