# Generated by Django 4.1 on 2022-12-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agf_assets', '0015_alter_area_region'),
        ('agf_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'Each'), (2, 'Length'), (3, 'Roll'), (4, 'Carton')])),
                ('part_no', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WOItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='agf_stores.item')),
                ('wo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agf_maintenance.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stores', to='agf_assets.area')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('min', models.PositiveIntegerField()),
                ('max', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=20, null=True)),
                ('comment', models.CharField(max_length=1000, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stocks', to='agf_stores.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stocks', to='agf_stores.store')),
            ],
        ),
    ]
