# Generated by Django 4.1 on 2022-12-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agf_stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='agf_stores.company'),
        ),
    ]
